INSERT INTO MOVIES (name,duration,reserved) VALUES ('Doom', 130, false);
INSERT INTO MOVIES (name,duration,reserved) VALUES ('Castle in the sky', 130, true);
INSERT INTO MOVIES (name,duration,reserved) VALUES ('Spirited Away', 130, false);
INSERT INTO MOVIES (name,duration,reserved) VALUES ('Captain America', 130, false);
INSERT INTO MOVIES (name,duration,reserved) VALUES ('The Avengers', 130, false);
INSERT INTO MOVIES (name,duration,reserved) VALUES ('Iron Man', 130, false);
INSERT INTO MOVIES (name,duration,reserved) VALUES ('Your Name', 130, false);
INSERT INTO MOVIES (name,duration,reserved) VALUES ('Kiki''s Delivery Service', 130, false);
INSERT INTO MOVIES (name,duration,reserved) VALUES ('Princess Mononoke', 130, false);
INSERT INTO RESERVATIONS (owner,reservedMovieId,timeCheckedOut,duration) VALUES ('Jacob', 2, TO_DATE('15/06/2015', 'DD/MM/YYYY'), 240000);